"""Baseline (no RAG) NutriBench task utilities.

Nutrient: controlled by inline config (generated by run_all_bench.py).
"""

import re
import sys
import os

_NUTRI_RAG_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _NUTRI_RAG_ROOT not in sys.path:
    sys.path.insert(0, _NUTRI_RAG_ROOT)

os.environ["NUTRI_TARGET"] = "energy"

from nutri_rag.bench.task_utils import process_results, clean_output, agg_mae, is_number  # noqa: F401


def doc_to_text_cot(doc):
    meal = doc["meal_description"]
    return (
        f'Query: "{meal}"\n'
        f"Answer: Let\'s think step by step."
    )
