landmarks:
  Start Point:
    x: 1.17
    y: 2.98
    description: "Start point"

  Playground:
    x: 2.73
    y: 7.94
    description: "Playground that have a large free space for the robot to move around"

  Boxun Desk:
    x: 0.94
    y: 1.83
    description: "Boxun Desk"

  Uttej Desk:
    x: -2.00
    y: 1.70
    description: "Uttej Desk"

  Front Door:
    x: -10.72
    y: 2.82
    description: "Front door area"

  Kitchen:
    x: -14.36
    y: 10.73
    description: "Kitchen area"