#!/usr/bin/env python3
"""Run all NutriBench benchmark combinations: 4 nutrients x 4 modes (baseline + v0/v1/v2).

Usage:
    # All 16 combinations (full dataset)
    python scripts/run_all_bench.py

    # Quick test with 100 samples
    python scripts/run_all_bench.py --limit 100

    # Specific nutrients or modes only
    python scripts/run_all_bench.py --nutrients carb protein --modes v1 v2

    # Include baseline (no RAG) runs
    python scripts/run_all_bench.py --modes baseline v0 v1 v2
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
NUTRI_RAG_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
ATLAS_ROOT = os.path.abspath(os.path.join(NUTRI_RAG_ROOT, "..", ".."))

ALL_NUTRIENTS = ["carb", "protein", "fat", "energy"]
ALL_MODES = ["baseline", "v0", "v1", "v2"]
RAG_MODES = ["v0", "v1", "v2"]


def run_rag_bench(mode, nutrient, limit, port):
    """Run a single RAG benchmark via run_bench.py."""
    cmd = [
        sys.executable, os.path.join(SCRIPT_DIR, "run_bench.py"),
        "--mode", mode,
        "--nutrient", nutrient,
        "--port", str(port),
    ]
    if limit:
        cmd += ["--limit", str(limit)]

    print(f"\n{'='*60}")
    print(f"  Running: mode={mode}, nutrient={nutrient}, limit={limit or 'all'}")
    print(f"{'='*60}\n")

    result = subprocess.run(cmd, cwd=NUTRI_RAG_ROOT)
    return result.returncode == 0


def run_baseline_bench(nutrient, limit, port):
    """Run baseline (no RAG) benchmark via lm_eval CLI.

    Generates a temporary task YAML with the correct nutrient prompt,
    then runs it via lm_eval.
    """
    # Generate baseline task files in a temp directory
    baseline_task_dir = os.path.join(NUTRI_RAG_ROOT, "tasks", "_baseline_temp")
    os.makedirs(baseline_task_dir, exist_ok=True)

    sys.path.insert(0, NUTRI_RAG_ROOT)
    from nutri_rag.bench.nutrient_prompts import build_system_prompt

    system_prompt = build_system_prompt(nutrient)
    indented = "\n".join("  " + line for line in system_prompt.split("\n"))

    # Write template YAML
    template_content = f"""dataset_path: dongx1997/NutriBench
dataset_name: v2
test_split: train
output_type: generate_until

description: |
{indented}

doc_to_text:  !function utils.doc_to_text_cot
doc_to_target: 0
process_results: !function utils.process_results

generation_kwargs:
  until: []
  do_sample: false
  temperature: 0.0
  max_gen_toks: 4096

metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: mae
    aggregation: mean
    higher_is_better: true

metadata:
  version: 1.0
"""
    with open(os.path.join(baseline_task_dir, "_default_template_yaml"), "w") as f:
        f.write(template_content)

    # Write task YAML
    with open(os.path.join(baseline_task_dir, "baseline.yaml"), "w") as f:
        f.write("task: nutribench_v2_baseline\ninclude: _default_template_yaml\n")

    # Write utils.py for baseline (no RAG, just CoT)
    utils_content = f'''"""Baseline (no RAG) NutriBench task utilities.

Nutrient: controlled by inline config (generated by run_all_bench.py).
"""

import re
import sys
import os

_NUTRI_RAG_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _NUTRI_RAG_ROOT not in sys.path:
    sys.path.insert(0, _NUTRI_RAG_ROOT)

os.environ["NUTRI_TARGET"] = "{nutrient}"

from nutri_rag.bench.task_utils import process_results, clean_output, agg_mae, is_number  # noqa: F401


def doc_to_text_cot(doc):
    meal = doc["meal_description"]
    return (
        f'Query: "{{meal}}"\\n'
        f"Answer: Let\\'s think step by step."
    )
'''
    with open(os.path.join(baseline_task_dir, "utils.py"), "w") as f:
        f.write(utils_content)

    # Symlink into lm-evaluation-harness
    lm_eval_dir = os.path.join(ATLAS_ROOT, "qwen_test", "lm-evaluation-harness")
    dst = os.path.join(lm_eval_dir, "lm_eval", "tasks", "nutribench", "v2", "_baseline_temp")
    if os.path.islink(dst):
        os.unlink(dst)
    elif os.path.exists(dst):
        import shutil
        shutil.rmtree(dst)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    os.symlink(baseline_task_dir, dst)

    # Run via lm_eval
    base_url = f"http://localhost:{port}/v1/chat/completions"

    print(f"\n{'='*60}")
    print(f"  Running: mode=baseline, nutrient={nutrient}, limit={limit or 'all'}")
    print(f"{'='*60}\n")

    os.environ["NUTRI_TARGET"] = nutrient

    sys.path.insert(0, lm_eval_dir)
    os.chdir(lm_eval_dir)

    import lm_eval
    from lm_eval.tasks.manager import TaskManager

    task_manager = TaskManager(include_path=baseline_task_dir)
    model_args = f"model=qwen3.5-9b,base_url={base_url},num_concurrent=6,max_retries=2"

    results = lm_eval.simple_evaluate(
        model="local-chat-completions",
        model_args=model_args,
        tasks=["nutribench_v2_baseline"],
        task_manager=task_manager,
        batch_size=1,
        random_seed=42,
        numpy_random_seed=42,
        torch_random_seed=42,
        fewshot_random_seed=42,
        log_samples=True,
        apply_chat_template=True,
        limit=limit,
    )

    # Save results
    output_dir = os.path.join(NUTRI_RAG_ROOT, "results")
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    out_file = os.path.join(output_dir, f"results_baseline_{nutrient}_{timestamp}.json")
    with open(out_file, "w") as f:
        save_data = {
            "mode": "baseline",
            "nutrient": nutrient,
            "results": results["results"],
            "configs": {k: str(v) for k, v in results.get("configs", {}).items()},
        }
        json.dump(save_data, f, indent=2, default=str)
    print(f"\nResults saved to {out_file}")

    if "samples" in results and results["samples"]:
        for tname, samples in results["samples"].items():
            samples_file = os.path.join(output_dir, f"samples_baseline_{nutrient}_{timestamp}.jsonl")
            with open(samples_file, "w") as f:
                for sample in samples:
                    f.write(json.dumps(sample, default=str) + "\n")
            print(f"Samples saved to {samples_file}")

    return True


def main():
    parser = argparse.ArgumentParser(description="Run all NutriBench benchmark combinations")
    parser.add_argument("--nutrients", nargs="+", choices=ALL_NUTRIENTS, default=ALL_NUTRIENTS,
                        help="Nutrients to evaluate (default: all)")
    parser.add_argument("--modes", nargs="+", choices=ALL_MODES, default=RAG_MODES,
                        help="Modes to run (default: v0 v1 v2). Use 'baseline' for no-RAG.")
    parser.add_argument("--limit", type=int, default=None,
                        help="Limit number of samples per run")
    parser.add_argument("--port", type=int, default=8080,
                        help="llama-server port (default: 8080)")
    args = parser.parse_args()

    total = len(args.nutrients) * len(args.modes)
    print(f"Running {total} benchmark combinations:")
    print(f"  Nutrients: {args.nutrients}")
    print(f"  Modes: {args.modes}")
    print(f"  Limit: {args.limit or 'all'}")
    print()

    results_summary = []
    for nutrient in args.nutrients:
        for mode in args.modes:
            start = datetime.now()
            if mode == "baseline":
                success = run_baseline_bench(nutrient, args.limit, args.port)
            else:
                success = run_rag_bench(mode, nutrient, args.limit, args.port)
            elapsed = (datetime.now() - start).total_seconds()
            results_summary.append({
                "mode": mode,
                "nutrient": nutrient,
                "success": success,
                "elapsed_s": round(elapsed, 1),
            })

    # Print summary table
    print(f"\n{'='*60}")
    print("  SUMMARY")
    print(f"{'='*60}")
    print(f"{'Mode':<15} {'Nutrient':<10} {'Status':<10} {'Time (s)':<10}")
    print("-" * 45)
    for r in results_summary:
        status = "OK" if r["success"] else "FAILED"
        print(f"{r['mode']:<15} {r['nutrient']:<10} {status:<10} {r['elapsed_s']:<10}")

    # Save summary
    output_dir = os.path.join(NUTRI_RAG_ROOT, "results")
    timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    summary_file = os.path.join(output_dir, f"run_all_summary_{timestamp}.json")
    with open(summary_file, "w") as f:
        json.dump(results_summary, f, indent=2)
    print(f"\nSummary saved to {summary_file}")


if __name__ == "__main__":
    main()
